

import Header from './../heder'
import Footer from './../footer'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function MarketingLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
      <Header/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
