

// import Header from '../heder'
import Footer from '../footer'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        
    
      {children}
      <Footer/>
      </body>
    </html>
  )
}
